/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnotatorDemoIndexRouteImport } from './routes/annotator-demo/index'
import { Route as AlignerDemoIndexRouteImport } from './routes/aligner-demo/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotatorDemoIndexRoute = AnnotatorDemoIndexRouteImport.update({
  id: '/annotator-demo/',
  path: '/annotator-demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignerDemoIndexRoute = AlignerDemoIndexRouteImport.update({
  id: '/aligner-demo/',
  path: '/aligner-demo/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aligner-demo/': typeof AlignerDemoIndexRoute
  '/annotator-demo/': typeof AnnotatorDemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aligner-demo': typeof AlignerDemoIndexRoute
  '/annotator-demo': typeof AnnotatorDemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aligner-demo/': typeof AlignerDemoIndexRoute
  '/annotator-demo/': typeof AnnotatorDemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aligner-demo/' | '/annotator-demo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aligner-demo' | '/annotator-demo'
  id: '__root__' | '/' | '/aligner-demo/' | '/annotator-demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignerDemoIndexRoute: typeof AlignerDemoIndexRoute
  AnnotatorDemoIndexRoute: typeof AnnotatorDemoIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotator-demo/': {
      id: '/annotator-demo/'
      path: '/annotator-demo'
      fullPath: '/annotator-demo/'
      preLoaderRoute: typeof AnnotatorDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aligner-demo/': {
      id: '/aligner-demo/'
      path: '/aligner-demo'
      fullPath: '/aligner-demo/'
      preLoaderRoute: typeof AlignerDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignerDemoIndexRoute: AlignerDemoIndexRoute,
  AnnotatorDemoIndexRoute: AnnotatorDemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
