[package]
name = "annotator-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Tauri shell for the Annotator desktop app."

[build-dependencies]
tauri-build.workspace = true

[dependencies]
lisca.workspace = true
tauri.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
