/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlignRouteImport } from './routes/align'
import { Route as AnnotateRouteImport } from './routes/annotate'
import { Route as AssayRouteImport } from './routes/assay'
import { Route as InfoRouteImport } from './routes/info'
import { Route as ResultRouteImport } from './routes/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignRoute = AlignRouteImport.update({
  id: '/align',
  path: '/align',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotateRoute = AnnotateRouteImport.update({
  id: '/annotate',
  path: '/annotate',
  getParentRoute: () => rootRouteImport,
} as any)
const AssayRoute = AssayRouteImport.update({
  id: '/assay',
  path: '/assay',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/annotate': typeof AnnotateRoute
  '/assay': typeof AssayRoute
  '/info': typeof InfoRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/annotate': typeof AnnotateRoute
  '/assay': typeof AssayRoute
  '/info': typeof InfoRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/annotate': typeof AnnotateRoute
  '/assay': typeof AssayRoute
  '/info': typeof InfoRoute
  '/result': typeof ResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/align' | '/annotate' | '/assay' | '/info' | '/result'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/align' | '/annotate' | '/assay' | '/info' | '/result'
  id: '__root__' | '/' | '/align' | '/annotate' | '/assay' | '/info' | '/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignRoute: typeof AlignRoute
  AnnotateRoute: typeof AnnotateRoute
  AssayRoute: typeof AssayRoute
  InfoRoute: typeof InfoRoute
  ResultRoute: typeof ResultRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/align': {
      id: '/align'
      path: '/align'
      fullPath: '/align'
      preLoaderRoute: typeof AlignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotate': {
      id: '/annotate'
      path: '/annotate'
      fullPath: '/annotate'
      preLoaderRoute: typeof AnnotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assay': {
      id: '/assay'
      path: '/assay'
      fullPath: '/assay'
      preLoaderRoute: typeof AssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignRoute: AlignRoute,
  AnnotateRoute: AnnotateRoute,
  AssayRoute: AssayRoute,
  InfoRoute: InfoRoute,
  ResultRoute: ResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
