/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlignRouteImport } from './routes/align'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AnnotateRouteImport } from './routes/annotate'
import { Route as AssayRouteImport } from './routes/assay'
import { Route as MetadataRouteImport } from './routes/metadata'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignRoute = AlignRouteImport.update({
  id: '/align',
  path: '/align',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotateRoute = AnnotateRouteImport.update({
  id: '/annotate',
  path: '/annotate',
  getParentRoute: () => rootRouteImport,
} as any)
const AssayRoute = AssayRouteImport.update({
  id: '/assay',
  path: '/assay',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/analysis': typeof AnalysisRoute
  '/annotate': typeof AnnotateRoute
  '/assay': typeof AssayRoute
  '/metadata': typeof MetadataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/analysis': typeof AnalysisRoute
  '/annotate': typeof AnnotateRoute
  '/assay': typeof AssayRoute
  '/metadata': typeof MetadataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/analysis': typeof AnalysisRoute
  '/annotate': typeof AnnotateRoute
  '/assay': typeof AssayRoute
  '/metadata': typeof MetadataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/align' | '/analysis' | '/annotate' | '/assay' | '/metadata'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/align' | '/analysis' | '/annotate' | '/assay' | '/metadata'
  id:
    | '__root__'
    | '/'
    | '/align'
    | '/analysis'
    | '/annotate'
    | '/assay'
    | '/metadata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignRoute: typeof AlignRoute
  AnalysisRoute: typeof AnalysisRoute
  AnnotateRoute: typeof AnnotateRoute
  AssayRoute: typeof AssayRoute
  MetadataRoute: typeof MetadataRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/align': {
      id: '/align'
      path: '/align'
      fullPath: '/align'
      preLoaderRoute: typeof AlignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotate': {
      id: '/annotate'
      path: '/annotate'
      fullPath: '/annotate'
      preLoaderRoute: typeof AnnotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assay': {
      id: '/assay'
      path: '/assay'
      fullPath: '/assay'
      preLoaderRoute: typeof AssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignRoute: AlignRoute,
  AnalysisRoute: AnalysisRoute,
  AnnotateRoute: AnnotateRoute,
  AssayRoute: AssayRoute,
  MetadataRoute: MetadataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
