/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultRouteImport } from './routes/result'
import { Route as InspectRouteImport } from './routes/inspect'
import { Route as InfoRouteImport } from './routes/info'
import { Route as AssayRouteImport } from './routes/assay'
import { Route as AlignRouteImport } from './routes/align'
import { Route as IndexRouteImport } from './routes/index'

const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectRoute = InspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const AssayRoute = AssayRouteImport.update({
  id: '/assay',
  path: '/assay',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignRoute = AlignRouteImport.update({
  id: '/align',
  path: '/align',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/assay': typeof AssayRoute
  '/info': typeof InfoRoute
  '/inspect': typeof InspectRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/assay': typeof AssayRoute
  '/info': typeof InfoRoute
  '/inspect': typeof InspectRoute
  '/result': typeof ResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/assay': typeof AssayRoute
  '/info': typeof InfoRoute
  '/inspect': typeof InspectRoute
  '/result': typeof ResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/align' | '/assay' | '/info' | '/inspect' | '/result'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/align' | '/assay' | '/info' | '/inspect' | '/result'
  id: '__root__' | '/' | '/align' | '/assay' | '/info' | '/inspect' | '/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignRoute: typeof AlignRoute
  AssayRoute: typeof AssayRoute
  InfoRoute: typeof InfoRoute
  InspectRoute: typeof InspectRoute
  ResultRoute: typeof ResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect': {
      id: '/inspect'
      path: '/inspect'
      fullPath: '/inspect'
      preLoaderRoute: typeof InspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assay': {
      id: '/assay'
      path: '/assay'
      fullPath: '/assay'
      preLoaderRoute: typeof AssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/align': {
      id: '/align'
      path: '/align'
      fullPath: '/align'
      preLoaderRoute: typeof AlignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignRoute: AlignRoute,
  AssayRoute: AssayRoute,
  InfoRoute: InfoRoute,
  InspectRoute: InspectRoute,
  ResultRoute: ResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
