// This file is generated by `cargo run -p lisca --features export-typescript --bin export-typescript`.
// Do not edit by hand.

// This file has been generated by Specta. Do not edit this file manually.
export type AlignGridCellCoord = {
	i: number,
	j: number,
};

export type AlignGridShape = AlignGridShape_Serialize | AlignGridShape_Deserialize;

export type AlignGridShape_Deserialize = "rect" | "square" | "hex";

export type AlignGridShape_Serialize = "rect" | "hex";

export type AlignGridState = AlignGridState_Serialize | AlignGridState_Deserialize;

export type AlignGridState_Deserialize = {
	enabled: boolean,
	shape: AlignGridShape_Deserialize,
	tx: number | null,
	ty: number | null,
	rotation: number | null,
	spacingA: number | null,
	spacingB: number | null,
	cellWidth: number | null,
	cellHeight: number | null,
	opacity: number | null,
};

export type AlignGridState_Serialize = {
	enabled: boolean,
	shape: AlignGridShape_Serialize,
	tx: number | null,
	ty: number | null,
	rotation: number | null,
	spacingA: number | null,
	spacingB: number | null,
	cellWidth: number | null,
	cellHeight: number | null,
	opacity: number | null,
};

export type AlignOutputPaths = {
	bbox: string,
	align: string,
	roi: string,
};

export type AlignerSource = { kind: "folder"; path: string; subfolderTemplate: string; filenameTemplate: string } | { kind: "tif"; path: string } | { kind: "jpg"; path: string } | { kind: "nd2"; path: string } | { kind: "czi"; path: string };

export type AnalysisCsvFile = {
	kind: string,
	fileName: string,
	path: string,
	csv: string,
};

export type AnalysisProgress = {
	requestId: string,
	status: AnalysisStatus,
	stage: AnalysisStage,
	progress: number | null,
	message: string | null,
	resultFiles?: AnalysisCsvFile[],
	error: string | null,
};

export type AnalysisProgressMessage = {
	type: string,
	progress: AnalysisProgress,
};

export type AnalysisStage = "queued" | "preparing" | "segment" | "timeseries" | "auc" | "fit" | "completed";

export type AnalysisStartRequest = {
	workspacePath: string,
	requestId: string,
};

export type AnalysisStatus = "queued" | "running" | "completed" | "error";

export type AnnotationLabel = {
	id: string,
	name: string,
	color: string,
};

export type AppId = "aligner" | "annotator" | "studio";

export type AutoExcludeHistogramBin = {
	start: number | null,
	end: number | null,
	count: number,
};

export type AutoExcludePreviewCell = {
	i: number,
	j: number,
	x: number,
	y: number,
	w: number,
	h: number,
};

export type AutoExcludePreviewCellScore = {
	i: number,
	j: number,
	score: number | null,
};

export type AutoExcludePreviewRequest = {
	source: AlignerSource,
	selection: FrameRequest,
	cells: AutoExcludePreviewCell[],
};

export type AutoExcludePreviewResponse = {
	eligibleCellCount: number,
	cellScores: AutoExcludePreviewCellScore[],
	histogramBins: AutoExcludeHistogramBin[],
	scoreMin: number | null,
	scoreMax: number | null,
	threshold: number | null,
};

export type ContrastWindow = {
	min: number,
	max: number,
};

export type CropOutputFormat = "tiff";

export type CropRoiProgress = {
	requestId: string,
	status: CropRoiStatus,
	position: number | null,
	completedPositions: number,
	totalPositions: number,
	completedRois: number,
	totalRois: number,
	message: string | null,
	error: string | null,
};

export type CropRoiProgressMessage = {
	type: string,
	progress: CropRoiProgress,
};

export type CropRoiRequest = {
	requestId: string,
	workspacePath: string,
	source: AlignerSource,
	positions: number[],
	overwrite: boolean,
	outputFormat?: CropOutputFormat,
};

export type CropRoiResponse = {
	requestId: string,
	status: CropRoiStatus,
};

export type CropRoiStatus = "queued" | "running" | "completed" | "cancelled" | "error";

export type FramePayload = {
	width: number,
	height: number,
	dataBase64: string,
	pixelType: string,
	contrastDomain: ContrastWindow,
	suggestedContrast: ContrastWindow,
	appliedContrast: ContrastWindow,
};

export type FrameRequest = {
	pos: number,
	channel: number,
	time: number,
	z: number,
};

export type Hello = {
	app: AppId,
	version: string,
};

export type HomeDirectoryResponse = {
	path: string,
};

export type HostFsEntry = {
	name: string,
	path: string,
	isDirectory: boolean,
};

export type HostListDirectoryResult = {
	path: string | null,
	parent: string | null,
	entries: HostFsEntry[],
};

export type LoadedRoiFrameAnnotation = {
	annotation: RoiFrameAnnotation,
	maskBase64Png: string | null,
};

export type ReadTextFileResponse = {
	contents: string,
};

export type RoiBbox = {
	roi: number,
	x: number,
	y: number,
	w: number,
	h: number,
};

export type RoiFrameAnnotation = {
	classificationLabelId: string | null,
	maskPath: string | null,
	updatedAt: string | null,
};

export type RoiFrameAnnotationPayload = {
	classificationLabelId: string | null,
	maskBase64Png: string | null,
};

export type RoiFrameRequest = {
	pos: number,
	roi: number,
	channel: number,
	time: number,
	z: number,
};

export type RoiIndexEntry = {
	roi: number,
	fileName: string,
	bbox: RoiBbox,
	shape: [number, number, number, number, number],
};

export type RoiIndexFile = {
	position: number,
	axisOrder: string,
	pageOrder: string[],
	timeCount: number,
	channelCount: number,
	zCount: number,
	source: AlignerSource,
	rois: RoiIndexEntry[],
};

export type RoiPosExistsResponse = {
	exists: boolean,
};

export type RoiPositionScan = {
	pos: number,
	source: AlignerSource,
	channels: number[],
	times: number[],
	zSlices: number[],
	rois: RoiIndexEntry[],
};

export type RoiWorkspaceScan = {
	positions: RoiPositionScan[],
};

export type SaveAssayJsonRequest = {
	saveTo: string,
	contents: string,
};

export type SaveAssayJsonResponse = {
	ok: boolean,
	path: string,
};

export type SaveBboxResponse = {
	ok: boolean,
	error: string | null,
};

export type SaveResultPdfRequest = {
	workspacePath: string,
	fileName: string,
	contentsBase64: string,
};

export type SaveResultPdfResponse = {
	ok: boolean,
	directory: string,
	path: string,
};

export type SavedAlignState = SavedAlignState_Serialize | SavedAlignState_Deserialize;

export type SavedAlignState_Deserialize = {
	grid: AlignGridState_Deserialize,
	excludedCells: AlignGridCellCoord[],
};

export type SavedAlignState_Serialize = {
	grid: AlignGridState_Serialize,
	excludedCells: AlignGridCellCoord[],
};

export type WorkspaceScan = {
	positions: number[],
	channels: number[],
	times: number[],
	zSlices: number[],
};
