//! Shared contracts, domain logic, and HTTP infrastructure for Lisca.

pub mod aligner;
pub mod analysis;
pub mod http;
pub mod image_source;
pub mod protocol;
pub mod roi;
pub mod smb;
mod tiff_io;

pub use protocol::AppId;

#[cfg(feature = "export-typescript")]
fn link_protocol_types_for_export() {
    fn register<T: specta::Type>() {}
    register::<protocol::Hello>();
    register::<protocol::SmbConnectRequest>();
    register::<protocol::SmbConnectResponse>();
    register::<protocol::SmbDisconnectRequest>();
    register::<protocol::CropRoiProgressMessage>();
    register::<protocol::AnalysisProgressMessage>();
    register::<protocol::AssayJsonFile>();
}

#[cfg(feature = "export-typescript")]
pub fn export_typescript_bindings() -> Result<(), Box<dyn std::error::Error>> {
    use std::path::PathBuf;

    use specta_typescript::Typescript;

    link_protocol_types_for_export();

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output = manifest_dir.join("../../packages/contracts/src/protocol.generated.ts");
    let header = "// This file is generated by `cargo run -p lisca --features export-typescript --bin export-typescript`.\n// Do not edit by hand.\n\n";
    let body = Typescript::default().export(&specta::collect(), specta_serde::PhasesFormat)?;
    std::fs::write(&output, format!("{header}{body}"))?;
    println!("wrote {}", output.display());
    Ok(())
}
