[package]
name = "lisca-tauri"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
tauri = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
default = []
