use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use clap::Args;
use plotters::prelude::*;

pub const HELP: &str = "Plot AUC summaries as one box plot per slide channel.";
const PYTHON_AUC_WIDTH: u32 = 1500;
const PYTHON_AUC_HEIGHT: u32 = 900;
const PYTHON_TITLE_FONT_SIZE: i32 = 25;
const PYTHON_LABEL_FONT_SIZE: i32 = 21;

#[derive(Clone, Debug, Args)]
#[command(about = HELP)]
pub struct PlotAucArgs {
    #[arg(help = "AUC summary CSV generated by delivery expression auc.")]
    pub auc_csv: PathBuf,
    #[arg(
        long,
        help = "Output PNG path. Default: same path as the AUC CSV with .png extension."
    )]
    pub output_plot: Option<PathBuf>,
    #[arg(long, default_value = "#c03a2b", help = "Plot color for the box fills.")]
    pub color: String,
    #[arg(long, default_value = "AUC by slide channel", help = "Optional plot title.")]
    pub title: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PlotAucRow {
    pub slide_channel: u32,
    pub auc: f64,
}

pub fn run_plot_auc(
    auc_csv: &Path,
    output_plot: Option<&Path>,
    color: &str,
    title: Option<&str>,
) -> Result<PathBuf, String> {
    let rows = load_auc_csv(auc_csv)?;
    let output = default_output_plot_path(auc_csv, output_plot);
    write_auc_boxplot(&rows, &output, color, title)?;
    Ok(output)
}

pub fn load_auc_csv(auc_csv: &Path) -> Result<Vec<PlotAucRow>, String> {
    let mut reader = csv::Reader::from_path(auc_csv).map_err(|err| err.to_string())?;
    let headers = reader.headers().map_err(|err| err.to_string())?.clone();
    let slide_channel_idx = headers.iter().position(|header| header == "slide_channel");
    let auc_idx = headers.iter().position(|header| header == "auc");
    let missing = [
        ("auc", auc_idx),
        ("slide_channel", slide_channel_idx),
    ]
    .into_iter()
    .filter_map(|(name, index)| index.is_none().then_some(name.to_string()))
    .collect::<Vec<_>>();
    if !missing.is_empty() {
        return Err(format!(
            "{} is missing required columns for AUC plotting: {:?}",
            auc_csv.display(),
            missing
        ));
    }

    let mut rows = Vec::new();
    for record in reader.records() {
        let record = record.map_err(|err| err.to_string())?;
        let slide_channel_raw = record
            .get(slide_channel_idx.unwrap())
            .unwrap_or_default()
            .trim()
            .to_string();
        let auc_raw = record.get(auc_idx.unwrap()).unwrap_or_default().trim().to_string();
        if slide_channel_raw.is_empty() || auc_raw.is_empty() {
            continue;
        }
        rows.push(PlotAucRow {
            slide_channel: slide_channel_raw
                .parse()
                .map_err(|_| format!("Invalid slide_channel value {slide_channel_raw:?}"))?,
            auc: auc_raw
                .parse()
                .map_err(|_| format!("Invalid auc value {auc_raw:?}"))?,
        });
    }
    if rows.is_empty() {
        return Err(format!(
            "{} has no AUC rows with slide_channel values",
            auc_csv.display()
        ));
    }
    rows.sort_by_key(|row| row.slide_channel);
    Ok(rows)
}

pub fn default_output_plot_path(auc_csv: &Path, output_plot: Option<&Path>) -> PathBuf {
    output_plot
        .map(PathBuf::from)
        .unwrap_or_else(|| auc_csv.with_extension("png"))
}

pub fn write_auc_boxplot(
    rows: &[PlotAucRow],
    output_plot: &Path,
    color: &str,
    title: Option<&str>,
) -> Result<(), String> {
    if let Some(parent) = output_plot.parent() {
        std::fs::create_dir_all(parent).map_err(|err| err.to_string())?;
    }
    let root = BitMapBackend::new(output_plot, (PYTHON_AUC_WIDTH, PYTHON_AUC_HEIGHT)).into_drawing_area();
    root.fill(&WHITE).map_err(|err| err.to_string())?;

    let mut grouped = BTreeMap::<u32, Vec<f64>>::new();
    for row in rows {
        grouped.entry(row.slide_channel).or_default().push(row.auc);
    }

    let values = grouped.values().flatten().copied().collect::<Vec<_>>();
    let y_min = values.iter().copied().fold(f64::INFINITY, f64::min);
    let y_max = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let (y_min, y_max) = if (y_max - y_min).abs() < f64::EPSILON {
        (y_min, y_max + 1.0)
    } else {
        let pad = (y_max - y_min) * 0.05;
        (y_min - pad, y_max + pad)
    };

    let mut chart = ChartBuilder::on(&root)
        .margin(20)
        .caption(
            title.unwrap_or("AUC by slide channel"),
            ("sans-serif", PYTHON_TITLE_FONT_SIZE),
        )
        .set_label_area_size(LabelAreaPosition::Left, 90)
        .set_label_area_size(LabelAreaPosition::Bottom, 85)
        .build_cartesian_2d(0.5f64..(grouped.len() as f64 + 0.5), y_min..y_max)
        .map_err(|err| err.to_string())?;
    chart
        .configure_mesh()
        .x_desc("slide channel")
        .y_desc("AUC")
        .label_style(("sans-serif", PYTHON_LABEL_FONT_SIZE))
        .axis_desc_style(("sans-serif", PYTHON_LABEL_FONT_SIZE))
        .x_labels(grouped.len())
        .x_label_formatter(&|value| {
            let index = value.round() as usize;
            if index == 0 || index > grouped.len() {
                String::new()
            } else {
                let slide_channel = grouped
                    .keys()
                    .nth(index - 1)
                    .copied();
                slide_channel
                    .and_then(|channel| {
                        grouped
                            .get(&channel)
                            .map(|values| format!("{channel}\n(n={})", values.len()))
                    })
                    .unwrap_or_default()
            }
        })
        .y_label_formatter(&super::plot_timeseries::scientific_tick_label)
        .disable_mesh()
        .draw()
        .map_err(|err| err.to_string())?;

    let fill = super::plot_timeseries::parse_color(color)?.mix(0.65);
    for (idx, values) in grouped.values().enumerate() {
        let x = idx as f64 + 1.0;
        let stats = boxplot_stats(values);
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x, stats.min), (x, stats.q1)],
                BLACK,
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x, stats.q3), (x, stats.max)],
                BLACK,
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x - 0.15, stats.min), (x + 0.15, stats.min)],
                BLACK,
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x - 0.15, stats.max), (x + 0.15, stats.max)],
                BLACK,
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(Rectangle::new(
                [(x - 0.25, stats.q1), (x + 0.25, stats.q3)],
                fill.filled(),
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x - 0.25, stats.median), (x + 0.25, stats.median)],
                BLACK.stroke_width(2),
            )))
            .map_err(|err| err.to_string())?;
    }
    root.present().map_err(|err| err.to_string())
}

pub fn format_written_auc_plot_message(output_plot: &Path) -> String {
    format!("Wrote plot: {}", output_plot.display())
}

pub fn execute(args: PlotAucArgs) -> Result<(), String> {
    let output = run_plot_auc(
        &args.auc_csv,
        args.output_plot.as_deref(),
        &args.color,
        args.title.as_deref(),
    )?;
    println!("{}", format_written_auc_plot_message(&output));
    Ok(())
}

#[derive(Clone, Copy, Debug)]
struct BoxplotStats {
    min: f64,
    q1: f64,
    median: f64,
    q3: f64,
    max: f64,
}

fn boxplot_stats(values: &[f64]) -> BoxplotStats {
    let mut sorted = values.to_vec();
    sorted.sort_by(|a, b| a.total_cmp(b));
    BoxplotStats {
        min: *sorted.first().unwrap_or(&0.0),
        q1: quantile(&sorted, 0.25),
        median: quantile(&sorted, 0.5),
        q3: quantile(&sorted, 0.75),
        max: *sorted.last().unwrap_or(&0.0),
    }
}

fn quantile(sorted: &[f64], q: f64) -> f64 {
    if sorted.len() <= 1 {
        return sorted.first().copied().unwrap_or(0.0);
    }
    let position = q * (sorted.len() - 1) as f64;
    let lower = position.floor() as usize;
    let upper = position.ceil() as usize;
    if lower == upper {
        sorted[lower]
    } else {
        let weight = position - lower as f64;
        sorted[lower] + (sorted[upper] - sorted[lower]) * weight
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn default_output_plot_path_uses_auc_name() {
        let path = default_output_plot_path(Path::new("/tmp/slide_auc.csv"), None);
        assert!(path.ends_with("slide_auc.png"));
    }

    #[test]
    fn auc_tick_label_includes_count() {
        let mut grouped = BTreeMap::<u32, Vec<f64>>::new();
        grouped.insert(0, vec![10.0, 12.0]);
        grouped.insert(1, vec![20.0]);
        let slide_channel = grouped.keys().nth(0).copied();
        let label = slide_channel
            .and_then(|channel| grouped.get(&channel).map(|values| format!("{channel}\n(n={})", values.len())))
            .unwrap_or_default();
        assert_eq!(label, "0\n(n=2)");
    }

    #[test]
    fn write_auc_boxplot_writes_png() {
        let tempdir = tempdir().unwrap();
        let output_plot = tempdir.path().join("auc.png");
        let rows = vec![
            PlotAucRow {
                slide_channel: 0,
                auc: 10.0,
            },
            PlotAucRow {
                slide_channel: 0,
                auc: 12.0,
            },
            PlotAucRow {
                slide_channel: 1,
                auc: 20.0,
            },
        ];

        write_auc_boxplot(&rows, &output_plot, "#c03a2b", Some("AUC by slide channel")).unwrap();

        assert!(output_plot.is_file());
    }
}
