use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use clap::Args;
use plotters::prelude::*;

pub const HELP: &str =
    "Plot fit summaries as one box plot per slide channel for each semantic fit parameter.";
const PYTHON_PLOT_WIDTH: u32 = 1500;
const PYTHON_PLOT_HEIGHT: u32 = 900;
const PYTHON_TITLE_FONT_SIZE: i32 = 25;
const PYTHON_LABEL_FONT_SIZE: i32 = 21;
const PARAMETERS: [(&str, &str); 5] = [
    ("intensity_offset", "intensity offset"),
    ("protein_decay_rate", "protein decay rate"),
    ("mrna_decay_rate", "mRNA decay rate"),
    ("expression_onset", "expression onset"),
    ("expression_amplitude", "expression amplitude"),
];

#[derive(Clone, Debug, Args)]
#[command(about = HELP)]
pub struct PlotFitArgs {
    #[arg(help = "Fit summary CSV generated by delivery expression fit.")]
    pub fit_csv: PathBuf,
    #[arg(
        long,
        help = "Directory for output PNGs. Default: same directory as the fit CSV."
    )]
    pub output_dir: Option<PathBuf>,
    #[arg(
        long,
        default_value = "#c03a2b",
        help = "Plot color for the box fills."
    )]
    pub color: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PlotFitRow {
    pub slide_channel: u32,
    pub values: BTreeMap<String, f64>,
}

pub fn run_plot_fit(
    fit_csv: &Path,
    output_dir: Option<&Path>,
    color: &str,
) -> Result<Vec<PathBuf>, String> {
    let rows = load_fit_csv(fit_csv)?;
    let output_paths = default_output_plot_paths(fit_csv, output_dir);
    let mut written = Vec::new();
    for (parameter, label) in PARAMETERS {
        let output_plot = output_paths
            .get(parameter)
            .ok_or_else(|| format!("Missing output path for parameter {parameter}"))?;
        write_fit_boxplot(
            &rows,
            parameter,
            label,
            output_plot,
            color,
            Some(&format!("{label} by slide channel")),
        )?;
        written.push(output_plot.clone());
    }
    Ok(written)
}

pub fn load_fit_csv(fit_csv: &Path) -> Result<Vec<PlotFitRow>, String> {
    let mut reader = csv::Reader::from_path(fit_csv).map_err(|err| err.to_string())?;
    let headers = reader.headers().map_err(|err| err.to_string())?.clone();

    let slide_channel_idx = headers.iter().position(|header| header == "slide_channel");
    let parameter_indices = PARAMETERS
        .into_iter()
        .map(|(parameter, _)| (parameter, headers.iter().position(|header| header == parameter)))
        .collect::<Vec<_>>();

    let mut missing = Vec::new();
    if slide_channel_idx.is_none() {
        missing.push("slide_channel".to_string());
    }
    missing.extend(
        parameter_indices
            .iter()
            .filter_map(|(parameter, idx)| idx.is_none().then_some((*parameter).to_string())),
    );
    if !missing.is_empty() {
        return Err(format!(
            "{} is missing required columns for fit plotting: {:?}",
            fit_csv.display(),
            missing
        ));
    }

    let mut rows = Vec::new();
    for record in reader.records() {
        let record = record.map_err(|err| err.to_string())?;
        let slide_channel_raw = record
            .get(slide_channel_idx.unwrap())
            .unwrap_or_default()
            .trim()
            .to_string();
        if slide_channel_raw.is_empty() {
            continue;
        }

        let slide_channel = slide_channel_raw
            .parse()
            .map_err(|_| format!("Invalid slide_channel value {slide_channel_raw:?}"))?;
        let mut values = BTreeMap::new();
        for (parameter, idx) in &parameter_indices {
            let raw = record.get(idx.unwrap()).unwrap_or_default().trim().to_string();
            if raw.is_empty() {
                continue;
            }
            let value = raw
                .parse()
                .map_err(|_| format!("Invalid {parameter} value {raw:?}"))?;
            values.insert((*parameter).to_string(), value);
        }
        rows.push(PlotFitRow {
            slide_channel,
            values,
        });
    }
    if rows.is_empty() {
        return Err(format!(
            "{} has no fit rows with slide_channel values",
            fit_csv.display()
        ));
    }
    rows.sort_by_key(|row| row.slide_channel);
    Ok(rows)
}

pub fn default_output_plot_paths(
    fit_csv: &Path,
    output_dir: Option<&Path>,
) -> BTreeMap<String, PathBuf> {
    let stem = fit_csv
        .file_stem()
        .and_then(|value| value.to_str())
        .unwrap_or("fit")
        .strip_suffix("_fit")
        .unwrap_or_else(|| fit_csv.file_stem().and_then(|value| value.to_str()).unwrap_or("fit"))
        .to_string();
    let destination_dir = output_dir
        .map(PathBuf::from)
        .unwrap_or_else(|| fit_csv.parent().unwrap_or_else(|| Path::new(".")).to_path_buf());
    PARAMETERS
        .into_iter()
        .map(|(parameter, _)| {
            (
                parameter.to_string(),
                destination_dir.join(format!("{stem}_{parameter}.png")),
            )
        })
        .collect()
}

pub fn write_fit_boxplot(
    rows: &[PlotFitRow],
    parameter: &str,
    ylabel: &str,
    output_plot: &Path,
    color: &str,
    title: Option<&str>,
) -> Result<(), String> {
    if let Some(parent) = output_plot.parent() {
        std::fs::create_dir_all(parent).map_err(|err| err.to_string())?;
    }

    let mut grouped = BTreeMap::<u32, Vec<f64>>::new();
    for row in rows {
        if let Some(value) = row.values.get(parameter) {
            grouped.entry(row.slide_channel).or_default().push(*value);
        }
    }
    if grouped.is_empty() {
        return Err(format!("No finite rows available to plot parameter {parameter:?}"));
    }

    let values = grouped.values().flatten().copied().collect::<Vec<_>>();
    let y_min = values.iter().copied().fold(f64::INFINITY, f64::min);
    let y_max = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let (y_min, y_max) = if (y_max - y_min).abs() < f64::EPSILON {
        (y_min, y_max + 1.0)
    } else {
        let pad = (y_max - y_min) * 0.05;
        (y_min - pad, y_max + pad)
    };

    let root =
        BitMapBackend::new(output_plot, (PYTHON_PLOT_WIDTH, PYTHON_PLOT_HEIGHT)).into_drawing_area();
    root.fill(&WHITE).map_err(|err| err.to_string())?;
    let mut chart = ChartBuilder::on(&root)
        .margin(20)
        .caption(
            title.unwrap_or(parameter),
            ("sans-serif", PYTHON_TITLE_FONT_SIZE),
        )
        .set_label_area_size(LabelAreaPosition::Left, 90)
        .set_label_area_size(LabelAreaPosition::Bottom, 85)
        .build_cartesian_2d(0.5f64..(grouped.len() as f64 + 0.5), y_min..y_max)
        .map_err(|err| err.to_string())?;
    chart
        .configure_mesh()
        .x_desc("slide channel")
        .y_desc(ylabel)
        .label_style(("sans-serif", PYTHON_LABEL_FONT_SIZE))
        .axis_desc_style(("sans-serif", PYTHON_LABEL_FONT_SIZE))
        .x_labels(grouped.len())
        .x_label_formatter(&|value| {
            let index = value.round() as usize;
            if index == 0 || index > grouped.len() {
                String::new()
            } else {
                let slide_channel = grouped.keys().nth(index - 1).copied();
                slide_channel
                    .and_then(|channel| {
                        grouped
                            .get(&channel)
                            .map(|channel_values| format!("{channel}\n(n={})", channel_values.len()))
                    })
                    .unwrap_or_default()
            }
        })
        .y_label_formatter(&super::plot_timeseries::scientific_tick_label)
        .disable_mesh()
        .draw()
        .map_err(|err| err.to_string())?;

    let fill = super::plot_timeseries::parse_color(color)?.mix(0.65);
    for (idx, channel_values) in grouped.values().enumerate() {
        let x = idx as f64 + 1.0;
        let stats = boxplot_stats(channel_values);
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x, stats.min), (x, stats.q1)],
                BLACK,
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x, stats.q3), (x, stats.max)],
                BLACK,
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x - 0.15, stats.min), (x + 0.15, stats.min)],
                BLACK,
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x - 0.15, stats.max), (x + 0.15, stats.max)],
                BLACK,
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(Rectangle::new(
                [(x - 0.25, stats.q1), (x + 0.25, stats.q3)],
                fill.filled(),
            )))
            .map_err(|err| err.to_string())?;
        chart
            .draw_series(std::iter::once(PathElement::new(
                vec![(x - 0.25, stats.median), (x + 0.25, stats.median)],
                BLACK.stroke_width(2),
            )))
            .map_err(|err| err.to_string())?;
    }

    root.present().map_err(|err| err.to_string())
}

pub fn format_written_fit_plot_messages(output_plots: &[PathBuf]) -> Vec<String> {
    output_plots
        .iter()
        .map(|output_plot| format!("Wrote plot: {}", output_plot.display()))
        .collect()
}

pub fn execute(args: PlotFitArgs) -> Result<(), String> {
    let outputs = run_plot_fit(&args.fit_csv, args.output_dir.as_deref(), &args.color)?;
    for message in format_written_fit_plot_messages(&outputs) {
        println!("{message}");
    }
    Ok(())
}

#[derive(Clone, Copy, Debug)]
struct BoxplotStats {
    min: f64,
    q1: f64,
    median: f64,
    q3: f64,
    max: f64,
}

fn boxplot_stats(values: &[f64]) -> BoxplotStats {
    let mut sorted = values.to_vec();
    sorted.sort_by(|a, b| a.total_cmp(b));
    BoxplotStats {
        min: *sorted.first().unwrap_or(&0.0),
        q1: quantile(&sorted, 0.25),
        median: quantile(&sorted, 0.5),
        q3: quantile(&sorted, 0.75),
        max: *sorted.last().unwrap_or(&0.0),
    }
}

fn quantile(sorted: &[f64], q: f64) -> f64 {
    if sorted.len() <= 1 {
        return sorted.first().copied().unwrap_or(0.0);
    }
    let position = q * (sorted.len() - 1) as f64;
    let lower = position.floor() as usize;
    let upper = position.ceil() as usize;
    if lower == upper {
        sorted[lower]
    } else {
        let weight = position - lower as f64;
        sorted[lower] + (sorted[upper] - sorted[lower]) * weight
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use super::*;

    #[test]
    fn default_output_plot_paths_strip_fit_suffix() {
        let fit_csv = Path::new("/tmp/slide_ch001_timeseries_fit.csv");

        let output_paths = default_output_plot_paths(fit_csv, None);

        assert_eq!(
            output_paths.get("intensity_offset").unwrap(),
            &PathBuf::from("/tmp/slide_ch001_timeseries_intensity_offset.png")
        );
        assert_eq!(
            output_paths.get("protein_decay_rate").unwrap(),
            &PathBuf::from("/tmp/slide_ch001_timeseries_protein_decay_rate.png")
        );
        assert_eq!(
            output_paths.get("mrna_decay_rate").unwrap(),
            &PathBuf::from("/tmp/slide_ch001_timeseries_mrna_decay_rate.png")
        );
        assert_eq!(
            output_paths.get("expression_onset").unwrap(),
            &PathBuf::from("/tmp/slide_ch001_timeseries_expression_onset.png")
        );
        assert_eq!(
            output_paths.get("expression_amplitude").unwrap(),
            &PathBuf::from("/tmp/slide_ch001_timeseries_expression_amplitude.png")
        );
    }

    #[test]
    fn load_fit_csv_requires_semantic_columns() {
        let tempdir = tempdir().unwrap();
        let fit_csv = tempdir.path().join("bad_fit.csv");
        fs::write(&fit_csv, "slide_channel,pos,roi,success\n0,1,2,true\n").unwrap();

        let error = load_fit_csv(&fit_csv).unwrap_err();

        assert!(error.contains("missing required columns"));
    }

    #[test]
    fn run_plot_fit_writes_all_parameter_plots() {
        let tempdir = tempdir().unwrap();
        let fit_csv = tempdir.path().join("slide_ch001_timeseries_fit.csv");
        fs::write(
            &fit_csv,
            concat!(
                "slide_channel,pos,roi,intensity_offset,protein_decay_rate,mrna_decay_rate,expression_onset,expression_amplitude,success\n",
                "0,12,0,2.0,0.05,0.35,0.0,40.0,true\n",
                "0,12,1,2.5,0.05,0.4,0.0,32.0,true\n",
                "1,14,0,3.0,0.05,0.7,0.0,16.0,true\n",
                "1,14,1,,,,,,false\n"
            ),
        )
        .unwrap();

        let outputs = run_plot_fit(&fit_csv, None, "#c03a2b").unwrap();

        assert_eq!(outputs.len(), PARAMETERS.len());
        for output in outputs {
            assert!(output.is_file());
        }
    }
}
