from __future__ import annotations

from pathlib import Path

import typer

from lisca.analysis.roi import (
    default_output_plot_path,
    load_timeseries_csv,
    write_trace_plot,
)

app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help=(
        "Plot all ROI traces from a long-form ROI timeseries CSV using low-opacity "
        "lines and no legend."
    ),
)


@app.command()
def cli(
    timeseries_csv: Path = typer.Argument(
        ...,
        exists=True,
        dir_okay=False,
        help="Long-form ROI timeseries CSV generated by the ROI extractor CLI.",
    ),
    output_plot: Path | None = typer.Option(
        None,
        "--output-plot",
        help="Output PNG path. Default: same path as the CSV with .png extension.",
    ),
    alpha: float = typer.Option(
        0.12,
        "--alpha",
        min=0.0,
        max=1.0,
        help="Per-trace opacity.",
    ),
    linewidth: float = typer.Option(
        1.0,
        "--linewidth",
        min=0.1,
        help="Per-trace line width.",
    ),
    color: str = typer.Option(
        "#c03a2b",
        "--color",
        help="Matplotlib color for all traces.",
    ),
    title: str | None = typer.Option(
        None,
        "--title",
        help="Optional plot title. Default: no title.",
    ),
) -> None:
    timeseries_csv = timeseries_csv.resolve()
    df = load_timeseries_csv(timeseries_csv)
    resolved_output_plot = default_output_plot_path(timeseries_csv, output_plot)
    write_trace_plot(
        df,
        resolved_output_plot,
        color=color,
        alpha=alpha,
        linewidth=linewidth,
        title=title,
    )
    print(f"Wrote plot: {resolved_output_plot}")


def main(argv: list[str] | None = None, *, prog_name: str = "delivery expression compare-timeseries") -> None:
    app(args=argv, prog_name=prog_name)


if __name__ == "__main__":
    main()
