from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
import typer


app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help="Plot AUC summaries as one box plot per slide channel.",
)


def run_plot_auc(
    auc_csv: Path,
    *,
    output_plot: Path | None,
    color: str,
    title: str | None,
) -> Path:
    resolved_auc_csv = auc_csv.resolve()
    df = load_auc_csv(resolved_auc_csv)
    resolved_output_plot = default_output_plot_path(resolved_auc_csv, output_plot)
    write_auc_boxplot(df, resolved_output_plot, color=color, title=title)
    return resolved_output_plot


def load_auc_csv(auc_csv: Path) -> pd.DataFrame:
    df = pd.read_csv(auc_csv)
    required = {"auc", "slide_channel"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"{auc_csv} is missing required columns for AUC plotting: {sorted(missing)}")
    df = df.dropna(subset=["slide_channel", "auc"]).copy()
    if df.empty:
        raise ValueError(f"{auc_csv} has no AUC rows with slide_channel values")
    df["slide_channel"] = df["slide_channel"].astype(int)
    df["auc"] = df["auc"].astype(float)
    return df.sort_values(["slide_channel"]).reset_index(drop=True)


def default_output_plot_path(auc_csv: Path, output_plot: Path | None) -> Path:
    plot_path = output_plot or auc_csv.with_suffix(".png")
    return plot_path.resolve()


def write_auc_boxplot(
    df: pd.DataFrame,
    output_plot: Path,
    *,
    color: str,
    title: str | None,
) -> None:
    slide_channels = sorted(df["slide_channel"].unique().tolist())
    grouped_values = [
        df.loc[df["slide_channel"] == slide_channel, "auc"].to_numpy(dtype=float)
        for slide_channel in slide_channels
    ]

    fig, ax = plt.subplots(figsize=(10, 6))
    boxplot = ax.boxplot(
        grouped_values,
        patch_artist=True,
        tick_labels=[str(value) for value in slide_channels],
    )
    for patch in boxplot["boxes"]:
        patch.set_facecolor(color)
        patch.set_alpha(0.65)
    for median in boxplot["medians"]:
        median.set_color("black")
        median.set_linewidth(1.2)

    ax.set_xlabel("slide channel")
    ax.set_ylabel("AUC")
    ax.grid(axis="y", alpha=0.2, linewidth=0.5)
    if title is not None:
        ax.set_title(title)

    output_plot.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_plot, dpi=150, bbox_inches="tight")
    plt.close(fig)


@app.command()
def cli(
    auc_csv: Path = typer.Argument(
        ...,
        exists=True,
        dir_okay=False,
        help="AUC summary CSV generated by delivery expression auc.",
    ),
    output_plot: Path | None = typer.Option(
        None,
        "--output-plot",
        help="Output PNG path. Default: same path as the AUC CSV with .png extension.",
    ),
    color: str = typer.Option(
        "#c03a2b",
        "--color",
        help="Matplotlib color for the box fills.",
    ),
    title: str | None = typer.Option(
        "AUC by slide channel",
        "--title",
        help="Optional plot title.",
    ),
) -> None:
    resolved_output_plot = run_plot_auc(
        auc_csv,
        output_plot=output_plot,
        color=color,
        title=title,
    )
    print(f"Wrote plot: {resolved_output_plot}")


def main(argv: list[str] | None = None, *, prog_name: str = "delivery expression plot-auc") -> None:
    app(args=argv, prog_name=prog_name)


if __name__ == "__main__":
    main()
