[package]
name = "annotator-tauri"
version = "0.3.2"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
annotator-server = { path = "../../server" }
lisca-tauri = { path = "../../../../crates/lisca-tauri" }
tauri = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }
