from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
import typer


app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help=(
        "Plot all ROI traces from a long-form stain timeseries CSV using low-opacity "
        "lines and no legend."
    ),
)


def load_timeseries(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    required = {"roi", "t", "corrected"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(
            f"{csv_path} is missing required columns for plotting: {sorted(missing)}"
    )
    return df.sort_values(["roi", "t"]).reset_index(drop=True)


def load_spikes(spike_csv: Path) -> pd.DataFrame:
    df = pd.read_csv(spike_csv)
    required = {"roi", "detected", "spike_t", "spike_value"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(
            f"{spike_csv} is missing required columns for spike overlay: {sorted(missing)}"
        )
    return df.loc[df["detected"].astype(bool)].sort_values("roi").reset_index(drop=True)


def default_output_plot_path(csv_path: Path, output_plot: Path | None) -> Path:
    plot_path = output_plot or csv_path.with_suffix(".png")
    return plot_path.resolve()


def write_trace_plot(
    df: pd.DataFrame,
    output_plot: Path,
    *,
    color: str,
    alpha: float,
    linewidth: float,
    spikes_df: pd.DataFrame | None,
    spike_color: str,
    spike_alpha: float,
    spike_marker_size: float,
    spike_marker_linewidth: float,
    title: str | None,
) -> None:
    fig, ax = plt.subplots(figsize=(12, 7))
    for _, roi_df in df.groupby("roi", sort=True):
        ax.plot(
            roi_df["t"],
            roi_df["corrected"],
            color=color,
            alpha=alpha,
            linewidth=linewidth,
        )

    if spikes_df is not None and not spikes_df.empty:
        ax.scatter(
            spikes_df["spike_t"],
            spikes_df["spike_value"],
            color=spike_color,
            alpha=spike_alpha,
            marker="x",
            s=spike_marker_size,
            linewidths=spike_marker_linewidth,
        )

    ax.set_xlabel("frame")
    ax.set_ylabel("sum - area*q25")
    ax.grid(alpha=0.2, linewidth=0.5)
    if title is not None:
        ax.set_title(title)

    output_plot.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_plot, dpi=150, bbox_inches="tight")
    plt.close(fig)


@app.command()
def cli(
    timeseries_csv: Path = typer.Argument(
        ...,
        exists=True,
        dir_okay=False,
        help="Long-form ROI timeseries CSV generated by apoptosis stain roi-timeseries.",
    ),
    output_plot: Path | None = typer.Option(
        None,
        "--output-plot",
        help="Output PNG path. Default: same path as the CSV with .png extension.",
    ),
    spike_csv: Path | None = typer.Option(
        None,
        "--spike-csv",
        exists=True,
        dir_okay=False,
        help="Optional spike CSV generated by apoptosis stain detect-spikes to overlay event markers.",
    ),
    alpha: float = typer.Option(
        0.12,
        "--alpha",
        min=0.0,
        max=1.0,
        help="Per-trace opacity.",
    ),
    linewidth: float = typer.Option(
        1.0,
        "--linewidth",
        min=0.1,
        help="Per-trace line width.",
    ),
    color: str = typer.Option(
        "#c03a2b",
        "--color",
        help="Matplotlib color for all traces.",
    ),
    spike_color: str = typer.Option(
        "#0b5fff",
        "--spike-color",
        help="Matplotlib color for spike markers.",
    ),
    spike_alpha: float = typer.Option(
        0.95,
        "--spike-alpha",
        min=0.0,
        max=1.0,
        help="Opacity for spike markers.",
    ),
    spike_marker_size: float = typer.Option(
        110.0,
        "--spike-marker-size",
        min=1.0,
        help="Marker area for spike crosses.",
    ),
    spike_marker_linewidth: float = typer.Option(
        2.2,
        "--spike-marker-linewidth",
        min=0.1,
        help="Line width for spike crosses.",
    ),
    title: str | None = typer.Option(
        None,
        "--title",
        help="Optional plot title. Default: no title.",
    ),
) -> None:
    timeseries_csv = timeseries_csv.resolve()
    df = load_timeseries(timeseries_csv)
    spikes_df = load_spikes(spike_csv.resolve()) if spike_csv is not None else None
    resolved_output_plot = default_output_plot_path(timeseries_csv, output_plot)
    write_trace_plot(
        df,
        resolved_output_plot,
        color=color,
        alpha=alpha,
        linewidth=linewidth,
        spikes_df=spikes_df,
        spike_color=spike_color,
        spike_alpha=spike_alpha,
        spike_marker_size=spike_marker_size,
        spike_marker_linewidth=spike_marker_linewidth,
        title=title,
    )
    print(f"Wrote plot: {resolved_output_plot}")


def main(argv: list[str] | None = None, *, prog_name: str = "apoptosis stain plot-traces") -> None:
    app(args=argv, prog_name=prog_name)
