/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChooseAssayRouteImport } from './routes/choose-assay'
import { Route as AlignPatternRouteImport } from './routes/align-pattern'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BasicInfo3RouteImport } from './routes/basic-info/3'
import { Route as BasicInfo2RouteImport } from './routes/basic-info/2'
import { Route as BasicInfo1RouteImport } from './routes/basic-info/1'

const ChooseAssayRoute = ChooseAssayRouteImport.update({
  id: '/choose-assay',
  path: '/choose-assay',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignPatternRoute = AlignPatternRouteImport.update({
  id: '/align-pattern',
  path: '/align-pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicInfo3Route = BasicInfo3RouteImport.update({
  id: '/basic-info/3',
  path: '/basic-info/3',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicInfo2Route = BasicInfo2RouteImport.update({
  id: '/basic-info/2',
  path: '/basic-info/2',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicInfo1Route = BasicInfo1RouteImport.update({
  id: '/basic-info/1',
  path: '/basic-info/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/align-pattern': typeof AlignPatternRoute
  '/choose-assay': typeof ChooseAssayRoute
  '/basic-info/1': typeof BasicInfo1Route
  '/basic-info/2': typeof BasicInfo2Route
  '/basic-info/3': typeof BasicInfo3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/align-pattern': typeof AlignPatternRoute
  '/choose-assay': typeof ChooseAssayRoute
  '/basic-info/1': typeof BasicInfo1Route
  '/basic-info/2': typeof BasicInfo2Route
  '/basic-info/3': typeof BasicInfo3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/align-pattern': typeof AlignPatternRoute
  '/choose-assay': typeof ChooseAssayRoute
  '/basic-info/1': typeof BasicInfo1Route
  '/basic-info/2': typeof BasicInfo2Route
  '/basic-info/3': typeof BasicInfo3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/align-pattern'
    | '/choose-assay'
    | '/basic-info/1'
    | '/basic-info/2'
    | '/basic-info/3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/align-pattern'
    | '/choose-assay'
    | '/basic-info/1'
    | '/basic-info/2'
    | '/basic-info/3'
  id:
    | '__root__'
    | '/'
    | '/align-pattern'
    | '/choose-assay'
    | '/basic-info/1'
    | '/basic-info/2'
    | '/basic-info/3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignPatternRoute: typeof AlignPatternRoute
  ChooseAssayRoute: typeof ChooseAssayRoute
  BasicInfo1Route: typeof BasicInfo1Route
  BasicInfo2Route: typeof BasicInfo2Route
  BasicInfo3Route: typeof BasicInfo3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/choose-assay': {
      id: '/choose-assay'
      path: '/choose-assay'
      fullPath: '/choose-assay'
      preLoaderRoute: typeof ChooseAssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/align-pattern': {
      id: '/align-pattern'
      path: '/align-pattern'
      fullPath: '/align-pattern'
      preLoaderRoute: typeof AlignPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-info/3': {
      id: '/basic-info/3'
      path: '/basic-info/3'
      fullPath: '/basic-info/3'
      preLoaderRoute: typeof BasicInfo3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-info/2': {
      id: '/basic-info/2'
      path: '/basic-info/2'
      fullPath: '/basic-info/2'
      preLoaderRoute: typeof BasicInfo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-info/1': {
      id: '/basic-info/1'
      path: '/basic-info/1'
      fullPath: '/basic-info/1'
      preLoaderRoute: typeof BasicInfo1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignPatternRoute: AlignPatternRoute,
  ChooseAssayRoute: ChooseAssayRoute,
  BasicInfo1Route: BasicInfo1Route,
  BasicInfo2Route: BasicInfo2Route,
  BasicInfo3Route: BasicInfo3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
