/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as RawRouteImport } from './routes/raw'
import { Route as IndexRouteImport } from './routes/index'

const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const RawRoute = RawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/raw': typeof RawRoute
  '/roi': typeof RoiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/raw': typeof RawRoute
  '/roi': typeof RoiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/raw': typeof RawRoute
  '/roi': typeof RoiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/raw' | '/roi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/raw' | '/roi'
  id: '__root__' | '/' | '/raw' | '/roi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RawRoute: typeof RawRoute
  RoiRoute: typeof RoiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw': {
      id: '/raw'
      path: '/raw'
      fullPath: '/raw'
      preLoaderRoute: typeof RawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RawRoute: RawRoute,
  RoiRoute: RoiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
