import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

import {
  KILLING_PLOTS,
  TRANSFECTION_AUC_CSV_COLUMNS,
  TRANSFECTION_FIT_CSV_COLUMNS,
  TRANSFECTION_PLOTS,
  TRANSFECTION_TRACE_CSV_COLUMNS,
} from "@lisca/analysis";
import {
  AssayJsonFileSchema,
  RoiIndexFileSchema,
  SavedAlignStateSchema,
  decodeJson,
  type AssayJsonFile,
  type RoiIndexFile,
  type SavedAlignState,
} from "@lisca/contracts";

import { colorFromName, encodeGrayPng, encodeGrayTiffPages, encodeRgbPng } from "./images";

export const FIXTURE_ASSAYS = ["transfection", "killing"] as const;
export const FIXTURE_STAGES = [
  "source",
  "assay",
  "aligned",
  "cropped",
  "annotated",
  "analyzed",
] as const;

export type FixtureAssay = (typeof FIXTURE_ASSAYS)[number];
export type FixtureStage = (typeof FIXTURE_STAGES)[number];

export type MaterializeOptions = {
  assay: FixtureAssay;
  stage: FixtureStage;
  out: string;
  force?: boolean;
};

export type MaterializeResult = {
  assay: FixtureAssay;
  stage: FixtureStage;
  out: string;
  files: string[];
};

const TRANSFECTION_FIXTURE_SAMPLE = "Mock (fixture)";

/** Killing fixture samples in assay order; each covers one Position. */
const KILLING_FIXTURE_SAMPLES = [
  { name: "Control (fixture)", position: 1 },
  { name: "CAR-T 1:4 (fixture)", position: 2 },
] as const;

/** Tiny, reviewable layout shared by both shipping assays. */
export const FIXTURE_LAYOUT = {
  positions: [1, 2] as const,
  rois: [1, 2] as const,
  times: [0, 1, 2] as const,
  channels: [0, 1] as const,
  z: 0,
  frameWidth: 16,
  frameHeight: 16,
  roiWidth: 4,
  roiHeight: 4,
  segmentationChannel: 0,
  signalChannel: 1,
  folderTemplate: {
    subfolder: "Pos{p}",
    filename: "img_channel{c}_position{p}_time{t}_z{z}",
  },
  boxes: [
    { roi: 1, x: 2, y: 2, w: 4, h: 4, i: 0, j: 0 },
    { roi: 2, x: 10, y: 2, w: 4, h: 4, i: 1, j: 0 },
  ],
} as const;

const BANNER = "Sample fixture data — not a real experiment.";

export function isFixtureAssay(value: string): value is FixtureAssay {
  return (FIXTURE_ASSAYS as readonly string[]).includes(value);
}

export function isFixtureStage(value: string): value is FixtureStage {
  return (FIXTURE_STAGES as readonly string[]).includes(value);
}

export function sourceFileName(pos: number, channel: number, time: number, z: number): string {
  return `img_channel${channel}_position${pos}_time${time}_z${z}.png`;
}

export function materializeFixture(options: MaterializeOptions): MaterializeResult {
  if (!isFixtureAssay(options.assay)) {
    throw new Error(`Unknown assay '${options.assay}'. Use ${FIXTURE_ASSAYS.join(" | ")}.`);
  }
  if (!isFixtureStage(options.stage)) {
    throw new Error(`Unknown stage '${options.stage}'. Use ${FIXTURE_STAGES.join(" | ")}.`);
  }

  const out = resolve(options.out);
  prepareOut(out, options.force === true);
  const files: string[] = [];
  const write = (rel: string, contents: string | Buffer) => {
    const path = join(out, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, contents);
    files.push(rel.replaceAll("\\", "/"));
  };

  write(
    "FIXTURE.txt",
    [
      BANNER,
      `assay: ${options.assay}`,
      `stage: ${options.stage}`,
      "generated by @lisca/fixtures",
      "",
    ].join("\n"),
  );

  if (options.stage === "source") {
    writeSourceFrames(write, "");
    return { assay: options.assay, stage: options.stage, out, files };
  }

  writeSourceFrames(write, "source");
  writeAssayJson(write, options.assay, out);
  if (stageAtLeast(options.stage, "aligned")) writeAlignment(write);
  if (stageAtLeast(options.stage, "cropped")) writeRoiStacks(write);
  if (stageAtLeast(options.stage, "annotated")) writeAnnotations(write, options.assay);
  if (stageAtLeast(options.stage, "analyzed")) writeAnalysisOutputs(write, options.assay);

  return { assay: options.assay, stage: options.stage, out, files };
}

function stageAtLeast(current: FixtureStage, needed: FixtureStage): boolean {
  return FIXTURE_STAGES.indexOf(current) >= FIXTURE_STAGES.indexOf(needed);
}

function prepareOut(out: string, force: boolean): void {
  if (!existsSync(out)) {
    mkdirSync(out, { recursive: true });
    return;
  }
  const entries = readdirSync(out);
  if (entries.length > 0 && !force) {
    throw new Error(
      `Output ${out} is not empty. Pass --force to overwrite files in a dedicated fixture directory.`,
    );
  }
}

function writeSourceFrames(write: WriteRel, prefix: string): void {
  const { positions, channels, times, z, frameWidth, frameHeight } = FIXTURE_LAYOUT;
  for (const pos of positions) {
    for (const channel of channels) {
      for (const time of times) {
        const rel = join(prefix, `Pos${pos}`, sourceFileName(pos, channel, time, z));
        write(rel, encodeGrayPng(frameWidth, frameHeight, sourcePixels(channel, time)));
      }
    }
  }
}

function sourcePixels(channel: number, time: number): Uint8Array {
  const { frameWidth, frameHeight, boxes } = FIXTURE_LAYOUT;
  const pixels = new Uint8Array(frameWidth * frameHeight).fill(24);
  const fill = channel === FIXTURE_LAYOUT.segmentationChannel ? 200 : 48 + time * 48;
  for (const box of boxes) {
    fillRect(pixels, frameWidth, box.x, box.y, box.w, box.h, fill);
  }
  return pixels;
}

function writeAssayJson(write: WriteRel, assay: FixtureAssay, workspacePath: string): void {
  const transfection = assay === "transfection";
  const assayJson: AssayJsonFile = {
    type: assay,
    name: transfection ? "Transfection (fixture)" : "Killing (fixture)",
    data: {
      type: "folder",
      path: join(workspacePath, "source"),
      template: { ...FIXTURE_LAYOUT.folderTemplate },
    },
    workspace: { path: workspacePath },
    interval: {
      value: transfection ? 10 : 15,
      unit: "minute",
    },
    samples: transfection
      ? [{ name: TRANSFECTION_FIXTURE_SAMPLE, positions: "1:2" }]
      : KILLING_FIXTURE_SAMPLES.map((sample) => ({
          name: sample.name,
          positions: String(sample.position),
        })),
    analysis: {
      ...(transfection ? { maxOnsetMinutes: 120, skipSegment: false } : {}),
      channels: {
        segmentation: FIXTURE_LAYOUT.segmentationChannel,
        signal: [FIXTURE_LAYOUT.signalChannel],
      },
    },
  };
  decodeJson(AssayJsonFileSchema, assayJson);
  write("assay.json", `${JSON.stringify(assayJson, null, 2)}\n`);
}

function writeAlignment(write: WriteRel): void {
  const align: SavedAlignState = {
    grid: {
      enabled: true,
      shape: "rect",
      tx: 2,
      ty: 2,
      rotation: 0,
      spacingA: 8,
      spacingB: 8,
      patternWidth: 4,
      patternHeight: 4,
      opacity: 0.6,
    },
    excludedPatterns: [],
  };
  decodeJson(SavedAlignStateSchema, align);

  const header = "roi,x,y,w,h";
  const rows = FIXTURE_LAYOUT.boxes.map((box) => `${box.roi},${box.x},${box.y},${box.w},${box.h}`);
  const csv = `${[header, ...rows].join("\n")}\n`;

  for (const pos of FIXTURE_LAYOUT.positions) {
    write(join("bbox", `Pos${pos}.csv`), csv);
    write(join("align", `Pos${pos}.json`), `${JSON.stringify(align, null, 2)}\n`);
  }
}

function writeRoiStacks(write: WriteRel): void {
  const { positions, times, channels, roiWidth, roiHeight, boxes } = FIXTURE_LAYOUT;
  const timeCount = times.length;
  const channelCount = channels.length;
  const zCount = 1;

  for (const pos of positions) {
    const index: RoiIndexFile = {
      position: pos,
      axisOrder: "TCZYX",
      timeCount,
      channelCount,
      zCount,
      timeIndices: [...times],
      rois: boxes.map((box) => ({
        roi: box.roi,
        fileName: `Roi${box.roi}.tif`,
        bbox: { roi: box.roi, x: box.x, y: box.y, w: box.w, h: box.h },
      })),
    };
    decodeJson(RoiIndexFileSchema, index);
    write(join("roi", `Pos${pos}`, "index.json"), `${JSON.stringify(index, null, 2)}\n`);

    for (const box of boxes) {
      const pages: Uint8Array[] = [];
      for (const time of times) {
        for (const channel of channels) {
          for (let zi = 0; zi < zCount; zi++) {
            pages.push(roiPage(channel, time, box.roi));
          }
        }
      }
      write(
        join("roi", `Pos${pos}`, `Roi${box.roi}.tif`),
        encodeGrayTiffPages(roiWidth, roiHeight, pages),
      );
    }
  }
}

function roiPage(channel: number, time: number, roi: number): Uint8Array {
  const { roiWidth, roiHeight, segmentationChannel } = FIXTURE_LAYOUT;
  const pixels = new Uint8Array(roiWidth * roiHeight).fill(12);
  const fill = channel === segmentationChannel ? 220 : Math.min(40 + time * 50 + roi * 8, 255);
  fillRect(pixels, roiWidth, 1, 1, 2, 2, fill);
  return pixels;
}

function writeAnnotations(write: WriteRel, assay: FixtureAssay): void {
  const labels =
    assay === "killing"
      ? [
          { id: "alive", name: "Alive (fixture)", color: "#22c55e" },
          { id: "dead", name: "Dead (fixture)", color: "#ef4444" },
        ]
      : [
          { id: "cell", name: "Cell (fixture)", color: "#22c55e" },
          { id: "empty", name: "Empty (fixture)", color: "#94a3b8" },
        ];
  write("annotations/labels.json", `${JSON.stringify({ labels }, null, 2)}\n`);

  const labelId = labels[0]?.id ?? "cell";
  const { roiWidth, roiHeight } = FIXTURE_LAYOUT;
  const mask = new Uint8Array(roiWidth * roiHeight);
  fillRect(mask, roiWidth, 1, 1, 2, 2, 1);
  const maskPng = encodeGrayPng(roiWidth, roiHeight, mask);

  for (const pos of FIXTURE_LAYOUT.positions) {
    for (const roi of FIXTURE_LAYOUT.rois) {
      const stem = "C0_T0_Z0";
      const dir = join("annotations", "roi", `Pos${pos}`, `Roi${roi}`);
      write(
        join(dir, `${stem}.json`),
        `${JSON.stringify(
          {
            schemaVersion: 1,
            classificationLabelId: labelId,
            maskFileName: `${stem}.png`,
            updatedAt: "unix:0",
          },
          null,
          2,
        )}\n`,
      );
      write(join(dir, `${stem}.png`), maskPng);
    }
  }
}

function writeAnalysisOutputs(write: WriteRel, assay: FixtureAssay): void {
  const { positions, rois, times, signalChannel, roiWidth, roiHeight } = FIXTURE_LAYOUT;
  if (assay === "transfection") {
    writeTransfectionAnalysis(write);
    for (const pos of positions) {
      for (const roi of rois) {
        const pages = times.map(() => {
          const pixels = new Uint8Array(roiWidth * roiHeight);
          fillRect(pixels, roiWidth, 1, 1, 2, 2, 1);
          return pixels;
        });
        write(
          join("mask", `Pos${pos}`, `Roi${roi}.tif`),
          encodeGrayTiffPages(roiWidth, roiHeight, pages),
        );
      }
    }
    writeTransfectionPlots(write);
    return;
  }

  for (const pos of positions) {
    const rows = [
      "roi,t,area,background,sum,corrected",
      ...rois.flatMap((roi) =>
        times.map((t) => {
          const area = roiWidth * roiHeight;
          const background = 10;
          const sum = 40 + roi * 10 + t * 40 + pos * 5;
          const corrected = sum - area * background;
          return `${roi},${t},${area},${background.toFixed(1)},${sum.toFixed(1)},${corrected.toFixed(1)}`;
        }),
      ),
    ];
    write(join("analysis", `Pos${pos}`, `ch${signalChannel}.csv`), `${rows.join("\n")}\n`);
  }
  for (const sampleDir of killingSampleDirnames()) {
    for (const plot of KILLING_PLOTS) {
      const [r, g, b] = colorFromName(plot.fileName);
      write(join("results", sampleDir, plot.fileName), encodeRgbPng(32, 18, r, g, b));
    }
  }
}

function killingSampleDirnames(): string[] {
  return KILLING_FIXTURE_SAMPLES.map((sample) => filesystemSafeSampleName(sample.name));
}

function transfectionSampleDirname(): string {
  return filesystemSafeSampleName(TRANSFECTION_FIXTURE_SAMPLE);
}

/** Match lisca-transfection `filesystem_safe_sample_name` for `results/<sample>/`. */
function filesystemSafeSampleName(name: string): string {
  let text = "";
  let lastUnderscore = false;
  for (const ch of name.trim()) {
    const replace =
      '<>:"/\\|?*'.includes(ch) || ch.charCodeAt(0) < 32 || /\s/.test(ch) ? "_" : null;
    if (replace) {
      if (!lastUnderscore && text.length > 0) {
        text += replace;
        lastUnderscore = true;
      }
    } else {
      text += ch;
      lastUnderscore = false;
    }
  }
  const trimmed = text.replace(/^[._\s]+|[._\s]+$/g, "").replace(/^\.+/, "");
  return trimmed.length === 0 ? "sample" : trimmed;
}

function writeTransfectionAnalysis(write: WriteRel): void {
  const { positions, rois, times, signalChannel } = FIXTURE_LAYOUT;
  for (const pos of positions) {
    const traces = [
      TRANSFECTION_TRACE_CSV_COLUMNS.join(","),
      ...rois.flatMap((roi) =>
        times.map((t) => {
          const area = 4;
          const background = 10;
          const sum = 40 + roi * 10 + t * 40;
          const corrected = sum - area * background;
          return `${roi},${t},${area},${background.toFixed(1)},${sum.toFixed(1)},${corrected.toFixed(1)}`;
        }),
      ),
    ];
    write(join("analysis", `Pos${pos}`, `ch${signalChannel}.csv`), `${traces.join("\n")}\n`);

    const auc = [
      TRANSFECTION_AUC_CSV_COLUMNS.join(","),
      ...rois.map((roi) => `${roi},${(80 + pos * 5 + roi * 3).toFixed(1)}`),
    ];
    write(join("analysis", `Pos${pos}`, "auc.csv"), `${auc.join("\n")}\n`);

    const fit = [
      TRANSFECTION_FIT_CSV_COLUMNS.join(","),
      ...rois.map((roi) =>
        [roi, (10 + roi).toFixed(1), (5 + pos).toFixed(1), "10.0", "1.39", "6.93", "true"].join(
          ",",
        ),
      ),
    ];
    write(join("analysis", `Pos${pos}`, "fit.csv"), `${fit.join("\n")}\n`);
  }
}

function writeTransfectionPlots(write: WriteRel): void {
  const sampleDir = transfectionSampleDirname();
  for (const plot of TRANSFECTION_PLOTS) {
    const [r, g, b] = colorFromName(plot.fileName);
    const rel =
      plot.scope === "sample"
        ? join("results", sampleDir, plot.fileName)
        : join("results", plot.fileName);
    write(rel, encodeRgbPng(32, 18, r, g, b));
  }
}

function fillRect(
  pixels: Uint8Array,
  width: number,
  x: number,
  y: number,
  w: number,
  h: number,
  value: number,
): void {
  for (let row = y; row < y + h; row++) {
    for (let col = x; col < x + w; col++) {
      pixels[row * width + col] = value;
    }
  }
}

type WriteRel = (rel: string, contents: string | Buffer) => void;

export function fixtureBanner(): string {
  return BANNER;
}

/** Relative paths an e2e/agent test can assert for a given stage. */
export function expectedKeyPaths(assay: FixtureAssay, stage: FixtureStage): string[] {
  const paths = ["FIXTURE.txt"];
  if (stage === "source") {
    paths.push(join("Pos1", sourceFileName(1, 0, 0, 0)));
    return paths.map((path) => path.replaceAll("\\", "/"));
  }
  paths.push("assay.json", join("source", "Pos1", sourceFileName(1, 0, 0, 0)));
  if (stageAtLeast(stage, "aligned")) paths.push("bbox/Pos1.csv", "align/Pos1.json");
  if (stageAtLeast(stage, "cropped")) paths.push("roi/Pos1/index.json", "roi/Pos1/Roi1.tif");
  if (stageAtLeast(stage, "annotated")) {
    paths.push("annotations/labels.json", "annotations/roi/Pos1/Roi1/C0_T0_Z0.json");
  }
  if (stageAtLeast(stage, "analyzed")) {
    if (assay === "transfection") {
      paths.push(
        `analysis/Pos1/ch${FIXTURE_LAYOUT.signalChannel}.csv`,
        "analysis/Pos1/auc.csv",
        "analysis/Pos1/fit.csv",
        "results/auc.png",
        "results/onset_time.png",
        `results/${transfectionSampleDirname()}/traces.png`,
      );
    } else {
      paths.push(
        `analysis/Pos1/ch${FIXTURE_LAYOUT.signalChannel}.csv`,
        `results/${killingSampleDirnames()[0]}/traces.png`,
        `results/${killingSampleDirnames()[0]}/traces_summary.png`,
      );
    }
  }
  return paths.map((path) => path.replaceAll("\\", "/"));
}
